### ISSUE TITLE
Evaluate polar for integration and compatibility testing with a diverse lightning network

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#515]
Polar allows us to easily create a lightning network with a diverse set of nodes supporting lnd, eclair and c-lightning. This is very useful for integration and compatibility testing and might even be suitable to replace our lightning faucet setup.

https://lightningpolar.com/

**Comment by holzeis** [comment]
@klochowicz Thanks for the hint.

**Comment by bonomat** [comment]
I've played around with it a bit, here are my findings: 

* Polar does not come with electrum, hence, we need to start it ourselves. This worked on a mac (I was not able to connect using the container IP as I could not attach the electrs container to the polar docker network. It should work in theory however
```
  electrs:    
    image: ghcr.io/vulpemventures/electrs:latest
    container_name: electrs
    entrypoint:
      - /build/electrs
    command:
      - -vvvv
      - --network
      - regtest
      - --daemon-rpc-addr
      - docker.for.mac.localhost:18443
      - --cookie
      - polaruser:polarpass
      - --http-addr
      - 0.0.0.0:30000
      - --electrum-rpc-addr
      - 0.0.0.0:50000
      - --cors
      - "*"
      - --jsonrpc-import
    ports:
      - "50000:50000"
      - "30000:30000"
    restart: unless-stopped
```
* Polar has a nice interface to start a series of LND/CLightning/Eclair nodes, however, you cannot open channels from within the UI to services outside of polar e.g. you can't open a channel to our coordinator. For that you will either need to use the rest interface or cli 
	* to connect to our coordinator: 
```
lncli --macaroonpath=/home/lnd/.lnd/data/chain/bitcoin/regtest/admin.macaroon \
      --tlscertpath=/home/lnd/.lnd/tls.cert \
      connect 02dd6abec97f9a748bf76ad502b004ce05d1b2d1f43a9e76bd7d85e767ffb022c9@docker.for.mac.localhost:9045
```
	* to open a channel to our coordinator (at the time of writing I failed doing so because of : `Peer's feerate much too high. Actual: 12500. Our expected upper limit: 6250`): 
	```
lncli --macaroonpath=/home/lnd/.lnd/data/chain/bitcoin/regtest/admin.macaroon \
      --tlscertpath=/home/lnd/.lnd/tls.cert \
      openchannel \
      --node_key=02dd6abec97f9a748bf76ad502b004ce05d1b2d1f43a9e76bd7d85e767ffb022c9 \
  	  --local_amt=10000000 --sat_per_byte=10
```
If we want to do load testing or similar this is going to be painful.
